We're going to try to implement the VAR(2) on the CTA data from say, two stations.

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
# Look-up stations
stations = pd.read_csv("../data/clean/station-lookup.csv")

def lookup(value):
    match = stations[stations["station_id"] == value]
    if not match.empty:
        print(match.iloc[0]["stationname"])
        return

    match = stations[stations["stationname"] == value]
    if not match.empty:
        print(match.iloc[0]["station_id"])
        return
    
    print(f"No match found for: {value}")

lookup(40010)
lookup("Austin-Forest Park")

Austin-Forest Park
40010


In [28]:
cta_data_red_weekly = pd.read_csv("../data/clean/cta-data-red-weekly.csv")
selected_stations = ['s_40080', 's_40100', 's_40190', 's_40240']

cta_data_red_weekly = cta_data_red_weekly.iloc[:, 1:]
cta_data_red_weekly = cta_data_red_weekly[selected_stations]
cta_data_red_weekly = cta_data_red_weekly.to_numpy()


[[ 567.71428571  388.85714286  194.71428571   15.71428571]
 [ 695.14285714  696.71428571 1160.14285714 1091.        ]
 [-194.         -176.14285714  -92.85714286  -76.71428571]
 ...
 [-141.85714286 -117.85714286  -49.42857143  -17.85714286]
 [-986.28571429 -702.         -481.         -622.        ]
 [ 549.71428571  337.          350.57142857  385.85714286]]


In [ ]:
from cmdstanpy import CmdStanModel, set_cmdstan_path
set_cmdstan_path("/deac/sta/classes/sta720/software/cmdstan/2.37.0")

# To write rest of Stan model...